default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: xozi_development
test:
  <<: *default
  database: xozi_test
production:
  <<: *default
  database: xozi_production
  username: xozi
  password: <%= ENV['XOZI_DATABASE_PASSWORD'] %>
